/**
 * Postal-letter PDF renderer (Epic #274 + content-enrichment follow-up).
 *
 * Single source of truth for the print layout — both the preview endpoint
 * (`POST /campaigns/:id/postal-preview`, sync, returns Buffer) and the
 * worker (`postal-export.ts`, async, streams to S3) call into this module
 * so the donor sees a byte-equivalent letter regardless of code path.
 *
 * Layout principles:
 *   - The **operator's organisation** is the visual identity, not Givernance.
 *     The header is the org name; we never put "Givernance" on the page.
 *   - The mission and campaign description give the donor the **why** in
 *     their own words, not boilerplate.
 *   - QR code lives in its own panel with the URL printed directly under
 *     it — the URL never overlaps the QR (a previous bug was the link
 *     drawn at the same Y as the QR raster).
 *   - The footer carries only the opaque reference + an optional preview
 *     watermark. No "generated by …" boilerplate.
 */

import { resolveCountryName } from "@givernance/shared/constants";
import type { Locale } from "@givernance/shared/i18n";
import { copyForLocale, type LetterCopy, MM_TO_PT } from "@givernance/shared/postal-print-layout";
import PDFDocument from "pdfkit";
import QRCode from "qrcode";

// Locale-driven copy + the mm-to-pt conversion factor live in
// `@givernance/shared/postal-print-layout` so the API preview and the
// worker bulk render share the exact same strings + measurement
// constants. Drift across the two would silently re-introduce the
// "preview lies about generation" bug PR #4 was opened to fix.
export type { LetterCopy };

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 width in points
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const QR_SIZE = 140;

// ── A4-folded-in-half geometry for C5 window envelope ─────────────────
//
// The letter is printed on a single A4 sheet (210×297mm), then folded
// once horizontally at the midline (y = 148.5mm). The folded letter
// (A5-landscape, 210×148.5mm) slips into a standard French C5 window
// envelope (162×229mm) with the **top half** of the original sheet
// becoming the visible cover.
//
// Layout split:
//   • Top half (0..148.5mm)    — letterhead + mission + recipient block
//                                (this is what the donor sees through
//                                 the C5 window before opening the env)
//   • Bottom half (148.5..297mm) — campaign title + description + body
//                                + QR panel (visible after unfolding)
//
// Address block lives in the top half, biased toward the right and
// vertically centered around the C5 window position. 1mm = 2.834645pt.
// Geometry: fold line at A4 midpoint (148.5mm). Address block sits in the
// top half (cover) at right-of-center, vertically centered around the C5
// envelope window. Campaign content flows starting just below the
// address block at 100mm — the body crosses the fold continuously, which
// reads as one A4 page when the donor unfolds the letter and avoids a
// 50mm dead zone between the address and the campaign title.
//
// `MM_TO_PT` is imported from `@givernance/shared/postal-print-layout`
// (single source of truth) so the API preview and the worker bulk
// render share the exact same conversion factor.
const ADDRESS_BLOCK_X = 110 * MM_TO_PT; // ≈ 312pt
const ADDRESS_BLOCK_Y = 60 * MM_TO_PT; // ≈ 170pt
const ADDRESS_BLOCK_WIDTH = 80 * MM_TO_PT; // ≈ 227pt
/** Y-coordinate where the campaign content starts (just below address). */
const CONTENT_TOP = 100 * MM_TO_PT; // ≈ 283pt

/**
 * Truthy when the recipient has the minimum address fields needed to
 * fit a French C5 window envelope. We deliberately don't insist on
 * `addressLine2` (rare) or `countryCode` (defaults to FR for domestic
 * mail) — but `addressLine1`, `postalCode`, and `city` are required.
 */
function hasWindowEnvelopeAddress(recipient: PostalLetterRecipient | null): boolean {
  if (!recipient) return false;
  return Boolean(
    recipient.addressLine1?.trim() && recipient.postalCode?.trim() && recipient.city?.trim(),
  );
}

export interface PostalLetterRecipient {
  firstName: string;
  lastName: string;
  email: string | null;
  /**
   * Optional postal address (Epic #274 follow-up). When all of
   * `addressLine1`, `postalCode`, and `city` are present, the renderer
   * positions a recipient block in the **C5 window** zone (top half,
   * right-of-center) so the letter fits in a C5 window envelope after
   * a single half-fold. When any required line is missing the block
   * is skipped and the cover panel still carries the org letterhead.
   */
  addressLine1: string | null;
  addressLine2: string | null;
  postalCode: string | null;
  city: string | null;
  countryCode: string | null;
}

export interface PostalLetterRenderInput {
  /** Operator-side organisation name — used as the letter's letterhead. */
  organisationName: string;
  /**
   * Optional org-logo bitmap (Epic #286 — the `pdf-letterhead` variant
   * out of the branding pipeline, 360×360 PNG @ 300 DPI). When present,
   * rendered top-left at the same Y-coordinate as the address block
   * (60mm) so the cover panel looks balanced through the C5 window
   * envelope. When null/undefined the layout is unchanged from pre-#286.
   */
  logoBuffer?: Buffer | null;
  /**
   * Free-form mission statement. Rendered in italic just under the
   * letterhead so the donor immediately sees "what does this org do".
   * Skipped when null/empty (operator hasn't filled the field yet).
   */
  organisationMission: string | null;
  /** Campaign name — drives the title under the letterhead. */
  campaignName: string;
  /**
   * Campaign description (admin source-of-truth). Inserted between the
   * salutation and the donate-call so the donor reads about the campaign
   * specifically, not just generic copy. Optional; falls back to the
   * generic body when absent.
   */
  campaignDescription: string | null;
  /** Personalisation block. `null` for door-drop campaigns. */
  recipient: PostalLetterRecipient | null;
  /** URL the QR code encodes — the operator-visible link printed below it. */
  qrPayload: string;
  /** Visible reference shown next to the QR (the opaque token in production). */
  qrReference: string;
  /**
   * Watermark for preview output. When `true`, a faint banner reminds
   * the operator this is fake data. Production exports always pass
   * `false`.
   */
  preview?: boolean;
  /**
   * Tenant default locale (`tenants.default_locale`) — drives the static
   * copy of the letter (salutation, body, call-to-scan, watermark).
   * Defaults to `fr` (the MVP market). Until campaigns carry their own
   * locale we render every letter in the org's preferred language.
   */
  locale?: Locale | null;
}

/**
 * Render the recipient address block in the C5 envelope window zone.
 * Country only printed for non-domestic mail; resolves the ISO code into
 * a human-readable country name (UPU S42 / La Poste cross-border guides
 * require the country name in full, never an ISO alpha-2). Pulled out of
 * `buildPostalLetterDoc` to keep that function under the cognitive-
 * complexity threshold; lockstep with worker/services/campaign-pdf.ts.
 */
function renderRecipientAddressBlock(
  doc: InstanceType<typeof PDFDocument>,
  recipient: NonNullable<PostalLetterRenderInput["recipient"]>,
  locale: PostalLetterRenderInput["locale"],
): void {
  doc.save().fillColor("#0f172a").font("Helvetica").fontSize(11);
  const lines: string[] = [`${recipient.firstName} ${recipient.lastName}`];
  if (recipient.addressLine1) lines.push(recipient.addressLine1);
  if (recipient.addressLine2) lines.push(recipient.addressLine2);
  lines.push(`${recipient.postalCode ?? ""} ${recipient.city ?? ""}`.trim());
  if (recipient.countryCode && recipient.countryCode.trim().toUpperCase() !== "FR") {
    const countryName = resolveCountryName(recipient.countryCode, locale);
    if (countryName) lines.push(countryName);
  }
  doc.text(lines.join("\n"), ADDRESS_BLOCK_X, ADDRESS_BLOCK_Y, {
    width: ADDRESS_BLOCK_WIDTH,
    lineGap: 1,
    align: "left",
  });
  doc.restore();
}

/**
 * Build the PDFKit document. Returns a `PDFDocument` instance the caller
 * can either pipe to S3 (worker) or sink into a Buffer (preview endpoint).
 * The doc is **not** ended here — the caller decides whether to call
 * `.end()` directly (worker streaming case) or via the buffer-collector
 * `renderPostalLetterToBuffer` helper below.
 */
async function buildPostalLetterDoc(
  input: PostalLetterRenderInput,
): Promise<InstanceType<typeof PDFDocument>> {
  const qrDataUrl = await QRCode.toDataURL(input.qrPayload, {
    width: 320,
    margin: 1,
    errorCorrectionLevel: "M",
  });
  // biome-ignore lint/style/noNonNullAssertion: data URI from QRCode.toDataURL always contains a comma separator
  const qrBuffer = Buffer.from(qrDataUrl.split(",")[1]!, "base64");

  const doc = new PDFDocument({
    size: "A4",
    margin: PAGE_MARGIN,
    info: {
      Title: `${input.organisationName} — ${input.campaignName}`,
      Author: input.organisationName,
      Subject: input.campaignName,
    },
  });

  // ── Preview watermark (fixed-position top banner) ────────────────────
  // Rendered as a fixed-position element BEFORE any flow content so it
  // never causes overflow to a 2nd page when the body is long. Drawn
  // with save()/restore() so the cursor stays put for the rest of the
  // layout. Production exports never set `preview: true`.
  if (input.preview) {
    doc
      .save()
      .fillColor("#b45309")
      .font("Helvetica-Oblique")
      .fontSize(8)
      .text(copyForLocale(input.locale).previewWatermark, PAGE_MARGIN, 10 * MM_TO_PT, {
        align: "center",
        width: CONTENT_WIDTH,
      })
      .restore();
  }

  // ── TOP HALF — COVER (visible through C5 window after fold) ──────────
  //
  // Three elements live above the fold line (y < 148.5mm):
  //   1. Org name centered at the top — the visual identity, biggest hit.
  //   2. Mission italic centered just below — answers "what does this org do".
  //   3. Recipient address block at right-of-center, middle of top half —
  //      aligns with the C5 window so the donor sees their own name
  //      through the envelope cut.
  // Org+mission are vertically above the address block (different y bands)
  // so the centered text never overlaps the right-aligned address column.

  // Letterhead — org name
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(22);
  doc.text(input.organisationName, PAGE_MARGIN, 25 * MM_TO_PT, {
    align: "center",
    width: CONTENT_WIDTH,
  });

  // Mission — under org name
  if (input.organisationMission && input.organisationMission.trim().length > 0) {
    doc.moveDown(0.3);
    doc.font("Helvetica-Oblique").fontSize(10).fillColor("#475569");
    doc.text(input.organisationMission.trim(), {
      align: "center",
      width: CONTENT_WIDTH,
    });
  }

  // ── Org logo (Epic #286) ────────────────────────────────────────────
  // Rendered top-left at the same Y as the address block (60mm) so the
  // cover panel reads as a balanced two-column layout through the C5
  // window: logo left, recipient right. The constant `60 * MM_TO_PT`
  // intentionally mirrors `ADDRESS_BLOCK_Y` exactly. PDFKit's
  // `doc.image` accepts PNG/JPEG only — the worker pipeline emits the
  // `pdf-letterhead` variant as PNG to satisfy that.
  if (input.logoBuffer) {
    const LOGO_X = PAGE_MARGIN; // ≈ 50pt
    const LOGO_Y = 60 * MM_TO_PT; // ≈ 170pt — mirrors ADDRESS_BLOCK_Y
    const LOGO_SIZE_MM = 30;
    const LOGO_SIZE_PT = LOGO_SIZE_MM * MM_TO_PT;
    doc.image(input.logoBuffer, LOGO_X, LOGO_Y, {
      fit: [LOGO_SIZE_PT, LOGO_SIZE_PT],
    });
  }

  // Recipient address block — middle-right of top half (C5 window zone)
  if (hasWindowEnvelopeAddress(input.recipient) && input.recipient) {
    renderRecipientAddressBlock(doc, input.recipient, input.locale);
  }

  // ── APPEAL CONTENT (flows continuously from just below the address) ──
  //
  // Starts at y=100mm — just below the address block. The body crosses
  // the fold line (148.5mm) seamlessly so when the donor unfolds the
  // letter it reads as one continuous A4 page. Avoids the dead-zone
  // problem of forcing content to start below the fold (the previous
  // 158mm offset left ~50mm of awkward whitespace between the address
  // and the campaign title). Everything fits on a single A4: title +
  // description + salutation + thanks + call-to-scan + QR panel.
  doc.x = PAGE_MARGIN;
  doc.y = CONTENT_TOP;

  // Campaign title
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(16);
  doc.text(input.campaignName, { align: "left" });
  doc.moveDown(0.6);

  // Campaign description — directly under the title, the operator's
  // actual copy. Skipped silently when the field is empty; in that case
  // the generic thanks-fallback further down carries the prose load.
  const hasDescription = Boolean(input.campaignDescription?.trim());
  if (hasDescription && input.campaignDescription) {
    doc.fillColor("#0f172a").font("Helvetica").fontSize(11);
    doc.text(input.campaignDescription.trim(), { align: "justify", lineGap: 2 });
    doc.moveDown(1.0);
  }

  // ── Locale-driven static copy ─────────────────────────────────────────
  const copy = copyForLocale(input.locale);

  // Salutation
  doc.fillColor("#0f172a").font("Helvetica").fontSize(12);
  if (input.recipient) {
    doc.text(copy.greetingNamed(input.recipient.firstName, input.recipient.lastName));
  } else {
    doc.text(copy.greetingDoorDrop);
  }
  doc.moveDown(0.8);

  // Thanks paragraph
  //  • Description was already shown above → short transition only.
  //  • No description → full generic fallback so the letter still feels
  //    like a real letter, not a bare "scan this code" instruction.
  if (hasDescription) {
    doc.text(
      input.recipient ? copy.thanksWithDescriptionNamed : copy.thanksWithDescriptionDoorDrop,
      { align: "justify", lineGap: 2 },
    );
  } else {
    doc.text(input.recipient ? copy.thanksFallbackNamed : copy.thanksFallbackDoorDrop, {
      align: "justify",
      lineGap: 2,
    });
  }
  doc.moveDown(0.8);

  // Call to scan
  doc.text(copy.callToScan, {
    align: "justify",
    lineGap: 2,
  });
  doc.moveDown(0.8);

  // ── QR panel — flows inline after the body. ──────────────────────────
  // Earlier draft pinned the panel to `page.height - margin - 220`, which
  // left a fat blank gap when the body was short. Now we draw the panel
  // exactly under the call-to-scan paragraph so the page reads top-down
  // without dead space. PDFKit auto-paginates if a particularly long
  // description pushes the panel below the bottom margin — there's no
  // overlap risk.
  const PANEL_HEIGHT = 200;
  const panelTopY = doc.y;
  const qrX = (PAGE_WIDTH - QR_SIZE) / 2;
  const qrY = panelTopY + 14;

  doc
    .roundedRect(PAGE_MARGIN, panelTopY, CONTENT_WIDTH, PANEL_HEIGHT, 12)
    .fillColor("#f8fafc")
    .fill();

  doc.image(qrBuffer, qrX, qrY, { width: QR_SIZE, height: QR_SIZE });

  const captionY = qrY + QR_SIZE + 10;
  doc
    .fillColor("#0f172a")
    .font("Helvetica-Bold")
    .fontSize(10)
    .text(input.qrPayload, PAGE_MARGIN, captionY, {
      align: "center",
      width: CONTENT_WIDTH,
      lineBreak: false,
    });
  doc
    .moveDown(0.4)
    .fillColor("#64748b")
    .font("Helvetica")
    .fontSize(8)
    .text(copy.referenceLabel(input.qrReference), {
      align: "center",
      width: CONTENT_WIDTH,
    });

  // Preview watermark already rendered at the top of the page (fixed
  // position, before flow content) so the QR panel reaches the bottom
  // of the page without ever forcing a 2nd-page spillover.

  return doc;
}

/**
 * Sync wrapper used by the preview endpoint — collects PDFKit chunks
 * into a single Buffer so Fastify can `reply.send(buf)` in one round-trip
 * without holding the doc stream open across the response boundary.
 */
export async function renderPostalLetterToBuffer(input: PostalLetterRenderInput): Promise<Buffer> {
  const doc = await buildPostalLetterDoc(input);

  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => {
      chunks.push(chunk as Buffer);
    });
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));
    doc.end();
  });
}

/**
 * Streaming variant used by the worker — returns the still-open PDFKit
 * stream so the caller can pipe it into `archiver.append(stream)` and
 * finalise the archive without ever materialising the PDF in memory.
 */
export async function buildPostalLetterStream(
  input: PostalLetterRenderInput,
): Promise<InstanceType<typeof PDFDocument>> {
  const doc = await buildPostalLetterDoc(input);
  doc.end();
  return doc;
}

// ─── Epic #318 PR #4 — Swiss QR-bill preview ───────────────────────────────
//
// `renderSwissQrBillPreviewToBuffer` and its private helpers now live in
// `./swiss-qr-bill-preview.ts` per ADR-027's single-path policy — the
// lockstep duplicate of `packages/worker/src/services/swiss-qr-bill.ts ::
// renderSwissQrBillPdf` is searchable by filename rather than buried
// inside `postal-pdf.ts`. Re-imported here for backwards-compatible
// access via the `postal-pdf` module surface.
export {
  renderSwissQrBillPreviewToBuffer,
  type SwissQrBillPreviewBankAccount,
  type SwissQrBillPreviewInput,
} from "./swiss-qr-bill-preview.js";
