/**
 * Sync postal-letter PDF renderer for the **preview** endpoint (Epic #274).
 *
 * Mirrors the worker's `services/campaign-pdf.ts` shape so the preview the
 * admin sees in the UI is byte-equivalent (modulo the QR token) to what the
 * batch worker would produce. We keep two copies on purpose:
 *   - the worker version streams directly to S3 (multipart upload), so it's
 *     a Readable producer;
 *   - the API version returns a Buffer so the preview route can `reply.send`
 *     in one round-trip without holding a streaming connection open.
 *
 * If the renderer ever grows non-trivial (templating, asset loading), the
 * shared bits should land in `@givernance/shared` instead of being copied
 * a third time.
 */

import PDFDocument from "pdfkit";
import QRCode from "qrcode";

export interface PostalPreviewInput {
  campaignName: string;
  /** URL the QR code points at — typically the campaign's public donation page. */
  qrPayload: string;
  /** Personalization for nominative campaigns. `null` for door-drop preview. */
  recipient: {
    firstName: string;
    lastName: string;
    email: string | null;
  } | null;
  /** Visible reference shown under the QR (the opaque token in production). */
  qrReference: string;
}

/** Render a single postal letter to a Buffer. Used by the preview endpoint. */
export async function renderPostalLetterToBuffer(input: PostalPreviewInput): Promise<Buffer> {
  const qrDataUrl = await QRCode.toDataURL(input.qrPayload, {
    width: 150,
    margin: 1,
    errorCorrectionLevel: "M",
  });
  // biome-ignore lint/style/noNonNullAssertion: data URI from QRCode.toDataURL always contains a comma separator
  const qrBuffer = Buffer.from(qrDataUrl.split(",")[1]!, "base64");

  const doc = new PDFDocument({ size: "A4", margin: 50 });

  // Buffer collection — we resolve when the doc emits `end`. PDFKit's
  // document is itself a Readable, so we just sink it into chunks.
  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => {
      chunks.push(chunk as Buffer);
    });
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));

    doc.fontSize(24).text("Givernance", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(16).text(input.campaignName, { align: "center" });
    doc.moveDown(2);

    if (input.recipient) {
      doc.fontSize(14).text("Dear Supporter", { underline: true });
      doc.fontSize(12).text(`Name: ${input.recipient.firstName} ${input.recipient.lastName}`);
      if (input.recipient.email) {
        doc.text(`Email: ${input.recipient.email}`);
      }
      doc.moveDown(1.5);
    }

    doc
      .fontSize(12)
      .text(
        input.recipient
          ? "Thank you for your continued support. We are reaching out to share our latest campaign and invite you to contribute to our mission."
          : "We are reaching out to share our latest campaign and invite you to support our mission. Your generosity makes a difference.",
      );
    doc.moveDown(1.5);

    doc.text("To learn more or donate, scan the QR code below:");
    doc.moveDown(1);

    doc.image(qrBuffer, doc.x, doc.y, { width: 150, height: 150 });
    doc.moveDown(8);

    doc.fontSize(10).text(`Reference: ${input.qrReference}`, { align: "center" });
    doc.moveDown(1);
    doc
      .fontSize(8)
      .fillColor("gray")
      .text("PREVIEW — sample data, this letter has not been registered.", {
        align: "center",
      });
    doc.moveDown(1);
    doc
      .fontSize(10)
      .fillColor("black")
      .text("This letter was generated by Givernance on behalf of your organization.", {
        align: "center",
      });

    doc.end();
  });
}
