/**
 * Postal-letter PDF renderer (Epic #274 + content-enrichment follow-up).
 *
 * Single source of truth for the print layout — both the preview endpoint
 * (`POST /campaigns/:id/postal-preview`, sync, returns Buffer) and the
 * worker (`postal-export.ts`, async, streams to S3) call into this module
 * so the donor sees a byte-equivalent letter regardless of code path.
 *
 * Layout principles:
 *   - The **operator's organisation** is the visual identity, not Givernance.
 *     The header is the org name; we never put "Givernance" on the page.
 *   - The mission and campaign description give the donor the **why** in
 *     their own words, not boilerplate.
 *   - QR code lives in its own panel with the URL printed directly under
 *     it — the URL never overlaps the QR (a previous bug was the link
 *     drawn at the same Y as the QR raster).
 *   - The footer carries only the opaque reference + an optional preview
 *     watermark. No "generated by …" boilerplate.
 */

import PDFDocument from "pdfkit";
import QRCode from "qrcode";

const PAGE_MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4 width in points
const CONTENT_WIDTH = PAGE_WIDTH - PAGE_MARGIN * 2;
const QR_SIZE = 140;

// ── Window-envelope address-block geometry (norme NF Z-10-011) ────────
//
// Standard French DL window envelope (110×220mm) has its window at
// roughly 20mm from left, 45mm from top, 90×35mm. After a Z-fold of an
// A4 sheet (3 panels of 99mm each), the *top* third of the page lands
// face-up inside the envelope window. So the recipient block on the A4
// page must sit at the same offset as the envelope window.
//
// 1mm = 2.834645 PDF points. We give the address block a 90×35mm box
// at (20mm, 50mm) from the top-left, leaving ~5mm of safe-zone padding
// on each side so a slight envelope misalignment doesn't clip the text.
const MM_TO_PT = 2.834645;
const ADDRESS_BLOCK_X = 20 * MM_TO_PT; // ≈ 57pt
const ADDRESS_BLOCK_Y = 50 * MM_TO_PT; // ≈ 142pt — distance from page top
const ADDRESS_BLOCK_WIDTH = 90 * MM_TO_PT; // ≈ 255pt
const ADDRESS_BLOCK_HEIGHT = 35 * MM_TO_PT; // ≈ 99pt
/** Where the body content starts when the address block was rendered. */
const CONTENT_TOP_AFTER_ADDRESS = ADDRESS_BLOCK_Y + ADDRESS_BLOCK_HEIGHT + 20;

/**
 * Truthy when the recipient has the minimum address fields needed to
 * fit a French DL window envelope. We deliberately don't insist on
 * `addressLine2` (rare) or `countryCode` (defaults to FR for domestic
 * mail) — but `addressLine1`, `postalCode`, and `city` are required.
 */
function hasWindowEnvelopeAddress(recipient: PostalLetterRecipient | null): boolean {
  if (!recipient) return false;
  return Boolean(
    recipient.addressLine1?.trim() && recipient.postalCode?.trim() && recipient.city?.trim(),
  );
}

export interface PostalLetterRecipient {
  firstName: string;
  lastName: string;
  email: string | null;
  /**
   * Optional postal address (Epic #274 follow-up). When all of
   * `addressLine1`, `postalCode`, and `city` are present, the renderer
   * positions a recipient block in the standard French DL window
   * (norme NF Z-10-011) so the letter fits in a window envelope after
   * a Z-fold. When any required line is missing the block is skipped
   * and the letterhead claims the top of the page as before.
   */
  addressLine1: string | null;
  addressLine2: string | null;
  postalCode: string | null;
  city: string | null;
  countryCode: string | null;
}

export interface PostalLetterRenderInput {
  /** Operator-side organisation name — used as the letter's letterhead. */
  organisationName: string;
  /**
   * Free-form mission statement. Rendered in italic just under the
   * letterhead so the donor immediately sees "what does this org do".
   * Skipped when null/empty (operator hasn't filled the field yet).
   */
  organisationMission: string | null;
  /** Campaign name — drives the title under the letterhead. */
  campaignName: string;
  /**
   * Campaign description (admin source-of-truth). Inserted between the
   * salutation and the donate-call so the donor reads about the campaign
   * specifically, not just generic copy. Optional; falls back to the
   * generic body when absent.
   */
  campaignDescription: string | null;
  /** Personalisation block. `null` for door-drop campaigns. */
  recipient: PostalLetterRecipient | null;
  /** URL the QR code encodes — the operator-visible link printed below it. */
  qrPayload: string;
  /** Visible reference shown next to the QR (the opaque token in production). */
  qrReference: string;
  /**
   * Watermark for preview output. When `true`, a faint banner reminds
   * the operator this is fake data. Production exports always pass
   * `false`.
   */
  preview?: boolean;
}

/**
 * Build the PDFKit document. Returns a `PDFDocument` instance the caller
 * can either pipe to S3 (worker) or sink into a Buffer (preview endpoint).
 * The doc is **not** ended here — the caller decides whether to call
 * `.end()` directly (worker streaming case) or via the buffer-collector
 * `renderPostalLetterToBuffer` helper below.
 */
async function buildPostalLetterDoc(
  input: PostalLetterRenderInput,
): Promise<InstanceType<typeof PDFDocument>> {
  const qrDataUrl = await QRCode.toDataURL(input.qrPayload, {
    width: 320,
    margin: 1,
    errorCorrectionLevel: "M",
  });
  // biome-ignore lint/style/noNonNullAssertion: data URI from QRCode.toDataURL always contains a comma separator
  const qrBuffer = Buffer.from(qrDataUrl.split(",")[1]!, "base64");

  const doc = new PDFDocument({
    size: "A4",
    margin: PAGE_MARGIN,
    info: {
      Title: `${input.organisationName} — ${input.campaignName}`,
      Author: input.organisationName,
      Subject: input.campaignName,
    },
  });

  // ── Recipient block (window envelope, optional) ───────────────────────
  // When the recipient has a usable address, we draw the recipient name
  // + address at the standard French DL window position. The letterhead
  // then starts BELOW the window so it never overlaps the envelope cut.
  const renderAddressBlock = hasWindowEnvelopeAddress(input.recipient);
  if (renderAddressBlock && input.recipient) {
    doc.save().fillColor("#0f172a").font("Helvetica").fontSize(11);
    const lines: string[] = [`${input.recipient.firstName} ${input.recipient.lastName}`];
    if (input.recipient.addressLine1) lines.push(input.recipient.addressLine1);
    if (input.recipient.addressLine2) lines.push(input.recipient.addressLine2);
    lines.push(`${input.recipient.postalCode ?? ""} ${input.recipient.city ?? ""}`.trim());
    if (input.recipient.countryCode && input.recipient.countryCode.trim().toUpperCase() !== "FR") {
      // Country only printed for non-domestic mail — domestic French
      // post never needs a country line, and adding one wastes a line
      // of the small address block.
      lines.push(input.recipient.countryCode.trim().toUpperCase());
    }
    doc.text(lines.join("\n"), ADDRESS_BLOCK_X, ADDRESS_BLOCK_Y, {
      width: ADDRESS_BLOCK_WIDTH,
      lineGap: 1,
      align: "left",
    });
    doc.restore();
    // Park the cursor below the address window so the rest of the
    // content doesn't try to paint into the envelope cut.
    doc.x = PAGE_MARGIN;
    doc.y = CONTENT_TOP_AFTER_ADDRESS;
  }

  // ── Letterhead ────────────────────────────────────────────────────────
  doc.fillColor("#0f172a");
  doc.font("Helvetica-Bold").fontSize(22);
  doc.text(input.organisationName, { align: "center" });
  if (input.organisationMission && input.organisationMission.trim().length > 0) {
    doc.moveDown(0.3);
    doc.font("Helvetica-Oblique").fontSize(10).fillColor("#475569");
    doc.text(input.organisationMission.trim(), { align: "center" });
  }

  // Thin rule
  doc.moveDown(0.8);
  const ruleY = doc.y;
  doc
    .strokeColor("#e2e8f0")
    .lineWidth(0.6)
    .moveTo(PAGE_MARGIN, ruleY)
    .lineTo(PAGE_MARGIN + CONTENT_WIDTH, ruleY)
    .stroke();
  doc.moveDown(1.4);

  // ── Campaign title ────────────────────────────────────────────────────
  doc.fillColor("#0f172a").font("Helvetica-Bold").fontSize(16);
  doc.text(input.campaignName, { align: "left" });
  doc.moveDown(1.2);

  // ── Salutation ────────────────────────────────────────────────────────
  doc.fillColor("#0f172a").font("Helvetica").fontSize(12);
  if (input.recipient) {
    const greeting = `Dear ${input.recipient.firstName} ${input.recipient.lastName},`;
    doc.text(greeting);
  } else {
    doc.text("Dear Supporter,");
  }
  doc.moveDown(0.8);

  // ── Body ──────────────────────────────────────────────────────────────
  // Two paths:
  //  • Operator filled `campaign.description` → use **their words**, full
  //    stop. We only add a brief warm transition before the call-to-scan,
  //    not a generic "Thank you for your continued support" wall, because
  //    that would read as filler bolted onto the operator's actual copy.
  //  • Operator did NOT fill the description → fall back to a generic
  //    paragraph so the letter still feels like a real letter, not a
  //    bare "scan this code" instruction.
  const hasDescription = Boolean(input.campaignDescription?.trim());
  if (hasDescription && input.campaignDescription) {
    doc.text(input.campaignDescription.trim(), { align: "justify", lineGap: 2 });
    doc.moveDown(0.8);
    doc.text(
      input.recipient
        ? "Thank you for your continued support — every contribution, big or small, makes a tangible difference."
        : "Every contribution, big or small, makes a tangible difference.",
      { align: "justify", lineGap: 2 },
    );
  } else {
    doc.text(
      input.recipient
        ? "Thank you for your continued support. Your generosity is what makes this campaign possible — every contribution, big or small, makes a tangible difference."
        : "Your support could make a real difference for this campaign. Every contribution, big or small, helps us go further.",
      { align: "justify", lineGap: 2 },
    );
  }
  doc.moveDown(0.8);
  doc.text("To learn more or contribute, scan the QR code below:", {
    align: "justify",
    lineGap: 2,
  });
  doc.moveDown(0.8);

  // ── QR panel — flows inline after the body. ──────────────────────────
  // Earlier draft pinned the panel to `page.height - margin - 220`, which
  // left a fat blank gap when the body was short. Now we draw the panel
  // exactly under the call-to-scan paragraph so the page reads top-down
  // without dead space. PDFKit auto-paginates if a particularly long
  // description pushes the panel below the bottom margin — there's no
  // overlap risk.
  const PANEL_HEIGHT = 200;
  const panelTopY = doc.y;
  const qrX = (PAGE_WIDTH - QR_SIZE) / 2;
  const qrY = panelTopY + 14;

  doc
    .roundedRect(PAGE_MARGIN, panelTopY, CONTENT_WIDTH, PANEL_HEIGHT, 12)
    .fillColor("#f8fafc")
    .fill();

  doc.image(qrBuffer, qrX, qrY, { width: QR_SIZE, height: QR_SIZE });

  const captionY = qrY + QR_SIZE + 10;
  doc
    .fillColor("#0f172a")
    .font("Helvetica-Bold")
    .fontSize(10)
    .text(input.qrPayload, PAGE_MARGIN, captionY, {
      align: "center",
      width: CONTENT_WIDTH,
      lineBreak: false,
    });
  doc
    .moveDown(0.4)
    .fillColor("#64748b")
    .font("Helvetica")
    .fontSize(8)
    .text(`Reference · ${input.qrReference}`, {
      align: "center",
      width: CONTENT_WIDTH,
    });

  if (input.preview) {
    doc
      .moveDown(0.4)
      .fillColor("#b45309")
      .font("Helvetica-Oblique")
      .fontSize(8)
      .text("PREVIEW — sample data, this letter has not been registered.", {
        align: "center",
        width: CONTENT_WIDTH,
      });
  }

  return doc;
}

/**
 * Sync wrapper used by the preview endpoint — collects PDFKit chunks
 * into a single Buffer so Fastify can `reply.send(buf)` in one round-trip
 * without holding the doc stream open across the response boundary.
 */
export async function renderPostalLetterToBuffer(input: PostalLetterRenderInput): Promise<Buffer> {
  const doc = await buildPostalLetterDoc(input);

  return new Promise<Buffer>((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on("data", (chunk) => {
      chunks.push(chunk as Buffer);
    });
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", (err) => reject(err));
    doc.end();
  });
}

/**
 * Streaming variant used by the worker — returns the still-open PDFKit
 * stream so the caller can pipe it into `archiver.append(stream)` and
 * finalise the archive without ever materialising the PDF in memory.
 */
export async function buildPostalLetterStream(
  input: PostalLetterRenderInput,
): Promise<InstanceType<typeof PDFDocument>> {
  const doc = await buildPostalLetterDoc(input);
  doc.end();
  return doc;
}
