/** Campaigns service — business logic for postal campaign operations */

import { campaignDocuments, campaigns, donations, outboxEvents } from "@givernance/shared/schema";
import type { Pagination } from "@givernance/shared/types";
import { and, eq, sql } from "drizzle-orm";
import { withTenantContext } from "../../lib/db.js";

export interface CreateCampaignInput {
  name: string;
  type: "nominative_postal" | "door_drop" | "digital";
  parentId?: string | null;
  costCents?: number | null;
}

export interface UpdateCampaignInput {
  name?: string;
  type?: "nominative_postal" | "door_drop" | "digital";
  status?: "draft" | "active" | "closed";
  parentId?: string | null;
  costCents?: number | null;
}

export interface ListCampaignsQuery {
  page: number;
  perPage: number;
}

/** List campaigns for an organization with pagination */
export async function listCampaigns(orgId: string, query: ListCampaignsQuery) {
  const { page, perPage } = query;
  const offset = (page - 1) * perPage;

  return withTenantContext(orgId, async (tx) => {
    const where = eq(campaigns.orgId, orgId);

    const [data, countResult] = await Promise.all([
      tx
        .select()
        .from(campaigns)
        .where(where)
        .orderBy(sql`${campaigns.createdAt} DESC`)
        .limit(perPage)
        .offset(offset),
      tx.select({ count: sql<number>`count(*)` }).from(campaigns).where(where),
    ]);

    const total = Number(countResult[0]?.count ?? 0);
    const pagination: Pagination = {
      page,
      perPage,
      total,
      totalPages: Math.ceil(total / perPage),
    };

    return { data, pagination };
  });
}

/** Custom error for campaign validation failures */
export class CampaignValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "CampaignValidationError";
  }
}

/** Create a new campaign */
export async function createCampaign(orgId: string, input: CreateCampaignInput, userId?: string) {
  return withTenantContext(orgId, async (tx) => {
    // Validate parentId if provided
    if (input.parentId) {
      const [parent] = await tx
        .select({ id: campaigns.id })
        .from(campaigns)
        .where(and(eq(campaigns.id, input.parentId), eq(campaigns.orgId, orgId)));
      if (!parent) {
        throw new CampaignValidationError("Parent campaign not found in this organization");
      }
    }

    const [campaign] = await tx
      .insert(campaigns)
      .values({
        orgId,
        name: input.name,
        type: input.type,
        parentId: input.parentId ?? null,
        costCents: input.costCents ?? null,
      })
      .returning();

    // Self-parent is also prevented by DB constraint, but the insert above
    // cannot produce a self-parent since the ID is generated by the DB.

    await tx.insert(outboxEvents).values({
      tenantId: orgId,
      type: "campaign.created",
      payload: {
        campaignId: campaign?.id,
        name: input.name,
        campaignType: input.type,
        createdBy: userId,
      },
    });

    return campaign;
  });
}

/** Get a single campaign by ID */
export async function getCampaign(orgId: string, id: string) {
  return withTenantContext(orgId, async (tx) => {
    const [row] = await tx
      .select()
      .from(campaigns)
      .where(and(eq(campaigns.id, id), eq(campaigns.orgId, orgId)));

    return row ?? null;
  });
}

/**
 * Detect cycles in the campaign parent hierarchy using a recursive CTE.
 * Returns true if setting `campaignId.parentId = newParentId` would create a cycle.
 */
async function wouldCreateCycle(
  tx: Parameters<Parameters<typeof withTenantContext>[1]>[0],
  orgId: string,
  campaignId: string,
  newParentId: string,
): Promise<boolean> {
  const result = await tx.execute(sql`
    WITH RECURSIVE ancestors AS (
      SELECT id, parent_id FROM campaigns WHERE id = ${newParentId} AND org_id = ${orgId}
      UNION ALL
      SELECT c.id, c.parent_id
      FROM campaigns c
      INNER JOIN ancestors a ON c.id = a.parent_id
    )
    SELECT 1 AS has_cycle FROM ancestors WHERE id = ${campaignId} LIMIT 1
  `);
  return result.rows.length > 0;
}

/** Update a campaign (partial update) */
export async function updateCampaign(
  orgId: string,
  id: string,
  input: UpdateCampaignInput,
  userId: string,
) {
  return withTenantContext(orgId, async (tx) => {
    const [existing] = await tx
      .select()
      .from(campaigns)
      .where(and(eq(campaigns.id, id), eq(campaigns.orgId, orgId)));

    if (!existing) return null;

    // Validate parentId: must not be self, must exist, must belong to same org, must not create cycle
    if (input.parentId !== undefined && input.parentId !== null) {
      if (input.parentId === id) {
        throw new CampaignValidationError("A campaign cannot be its own parent");
      }
      const [parent] = await tx
        .select({ id: campaigns.id })
        .from(campaigns)
        .where(and(eq(campaigns.id, input.parentId), eq(campaigns.orgId, orgId)));
      if (!parent) {
        throw new CampaignValidationError("Parent campaign not found in this organization");
      }
      // Multi-level cycle detection: walk ancestors of newParentId to check if campaignId is reachable
      if (await wouldCreateCycle(tx, orgId, id, input.parentId)) {
        throw new CampaignValidationError(
          "Setting this parent would create a cycle in the campaign hierarchy",
        );
      }
    }

    const [updated] = await tx
      .update(campaigns)
      .set({ ...input, updatedAt: new Date() })
      .where(and(eq(campaigns.id, id), eq(campaigns.orgId, orgId)))
      .returning();

    await tx.insert(outboxEvents).values({
      tenantId: orgId,
      type: "campaign.updated",
      payload: { campaignId: id, changes: input, updatedBy: userId },
    });

    return updated;
  });
}

/** Close (soft-delete) a campaign by setting status to 'closed' */
export async function closeCampaign(orgId: string, id: string, userId: string) {
  return withTenantContext(orgId, async (tx) => {
    const [existing] = await tx
      .select()
      .from(campaigns)
      .where(and(eq(campaigns.id, id), eq(campaigns.orgId, orgId)));

    if (!existing) return null;

    const now = new Date();
    const [closed] = await tx
      .update(campaigns)
      .set({ status: "closed", updatedAt: now })
      .where(and(eq(campaigns.id, id), eq(campaigns.orgId, orgId)))
      .returning();

    await tx.insert(outboxEvents).values({
      tenantId: orgId,
      type: "campaign.closed",
      payload: {
        campaignId: id,
        closedBy: userId,
      },
    });

    return closed;
  });
}

/** Get campaign stats: total raised, donation count, unique donors */
export async function getCampaignStats(orgId: string, campaignId: string) {
  return withTenantContext(orgId, async (tx) => {
    const [campaign] = await tx
      .select()
      .from(campaigns)
      .where(and(eq(campaigns.id, campaignId), eq(campaigns.orgId, orgId)));

    if (!campaign) return null;

    const [stats] = await tx
      .select({
        totalRaisedCents: sql<number>`COALESCE(SUM(${donations.amountBaseCents}), 0)`,
        donationCount: sql<number>`COUNT(${donations.id})`,
        uniqueDonors: sql<number>`COUNT(DISTINCT ${donations.constituentId})`,
      })
      .from(donations)
      .where(and(eq(donations.campaignId, campaignId), eq(donations.orgId, orgId)));

    return {
      campaignId,
      totalRaisedCents: Number(stats?.totalRaisedCents ?? 0),
      donationCount: Number(stats?.donationCount ?? 0),
      uniqueDonors: Number(stats?.uniqueDonors ?? 0),
    };
  });
}

/** Get campaign ROI: (totalRaised - costCents) / costCents */
export async function getCampaignRoi(orgId: string, campaignId: string) {
  return withTenantContext(orgId, async (tx) => {
    const [campaign] = await tx
      .select()
      .from(campaigns)
      .where(and(eq(campaigns.id, campaignId), eq(campaigns.orgId, orgId)));

    if (!campaign) return null;

    const [stats] = await tx
      .select({
        totalRaisedCents: sql<number>`COALESCE(SUM(${donations.amountBaseCents}), 0)`,
      })
      .from(donations)
      .where(and(eq(donations.campaignId, campaignId), eq(donations.orgId, orgId)));

    const totalRaisedCents = Number(stats?.totalRaisedCents ?? 0);
    const costCents = campaign.costCents;
    const roi =
      costCents != null && costCents > 0 ? (totalRaisedCents - costCents) / costCents : null;

    return {
      campaignId,
      totalRaisedCents,
      costCents: costCents ?? null,
      roi,
    };
  });
}

/** Request document generation for a campaign — emits CampaignDocumentsRequested event transactionally */
export async function requestCampaignDocuments(
  orgId: string,
  userId: string,
  campaignId: string,
  constituentIds: string[],
) {
  return withTenantContext(orgId, async (tx) => {
    // Verify campaign exists and belongs to this org
    const [campaign] = await tx
      .select()
      .from(campaigns)
      .where(and(eq(campaigns.id, campaignId), eq(campaigns.orgId, orgId)));

    if (!campaign) return null;

    // For door_drop, constituentIds is expected to be empty
    const ids = campaign.type === "door_drop" ? [] : constituentIds;

    // Create placeholder document records
    if (campaign.type === "door_drop") {
      await tx.insert(campaignDocuments).values({
        orgId,
        campaignId,
        constituentId: null,
        s3Path: "pending",
        status: "pending",
      });
    } else {
      if (ids.length > 0) {
        await tx.insert(campaignDocuments).values(
          ids.map((cId) => ({
            orgId,
            campaignId,
            constituentId: cId,
            s3Path: "pending",
            status: "pending" as const,
          })),
        );
      }
    }

    // Emit domain event in the same transaction
    await tx.insert(outboxEvents).values({
      tenantId: orgId,
      type: "campaign.documents_requested",
      payload: {
        campaignId,
        constituentIds: ids,
        campaignType: campaign.type,
        requestedBy: userId,
      },
    });

    return { campaignId, documentCount: campaign.type === "door_drop" ? 1 : ids.length };
  });
}
