/** Campaign PDF generation service — renders personalized A4 letters with QR codes */

import PDFDocument from "pdfkit";
import QRCode from "qrcode";

export interface CampaignLetterData {
  campaignName: string;
  orgId: string;
  qrCode: string;
  /** Constituent info — null for door_drop campaigns */
  constituent: {
    firstName: string;
    lastName: string;
    email: string | null;
  } | null;
}

/** Generate a campaign letter PDF with an embedded QR code */
export async function generateCampaignLetterPdf(data: CampaignLetterData): Promise<Buffer> {
  // Generate QR code as a data URI (PNG)
  const qrDataUrl = await QRCode.toDataURL(data.qrCode, {
    width: 150,
    margin: 1,
    errorCorrectionLevel: "M",
  });

  // biome-ignore lint/style/noNonNullAssertion: data URI from QRCode.toDataURL always contains a comma separator
  const qrBuffer = Buffer.from(qrDataUrl.split(",")[1]!, "base64");

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: "A4", margin: 50 });
    const chunks: Buffer[] = [];

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    // Header
    doc.fontSize(24).text("Givernance", { align: "center" });
    doc.moveDown(0.5);
    doc.fontSize(16).text(data.campaignName, { align: "center" });
    doc.moveDown(2);

    // Personalized content (nominative campaigns)
    if (data.constituent) {
      doc.fontSize(14).text("Dear Supporter", { underline: true });
      doc.fontSize(12).text(`Name: ${data.constituent.firstName} ${data.constituent.lastName}`);
      if (data.constituent.email) {
        doc.text(`Email: ${data.constituent.email}`);
      }
      doc.moveDown(1.5);
    }

    // Body text
    doc
      .fontSize(12)
      .text(
        data.constituent
          ? "Thank you for your continued support. We are reaching out to share our latest campaign and invite you to contribute to our mission."
          : "We are reaching out to share our latest campaign and invite you to support our mission. Your generosity makes a difference.",
      );
    doc.moveDown(1.5);

    doc.text("To learn more or donate, scan the QR code below:");
    doc.moveDown(1);

    // Embed QR code image
    doc.image(qrBuffer, doc.x, doc.y, { width: 150, height: 150 });
    doc.moveDown(8);

    // QR code reference
    doc.fontSize(10).text(`Reference: ${data.qrCode}`, { align: "center" });
    doc.moveDown(2);

    // Footer
    doc
      .fontSize(10)
      .text("This letter was generated by Givernance on behalf of your organization.", {
        align: "center",
      });

    doc.end();
  });
}
