/**
 * Campaign PDF generation — used by the synchronous preview endpoint
 * (Epic #274). The asynchronous mass generation lives in the worker
 * package (`@givernance/worker/services/campaign-pdf`); we duplicate
 * the formatting here rather than crossing the package boundary so
 * the API stays runtime-independent of the worker.
 *
 * If the layout diverges between API preview and worker bulk renders,
 * the bug is "preview lies about the real letter" — the worker is
 * the source of truth. Update both files in lockstep.
 */

import PDFDocument from "pdfkit";
import QRCode from "qrcode";

export interface CampaignLetterPreviewData {
  campaignName: string;
  qrPayload: string;
  /** When `null`, renders the door-drop generic version (no name salutation). */
  constituent: {
    firstName: string;
    lastName: string;
    email: string | null;
  } | null;
}

/**
 * Build a campaign letter PDF as a readable PDFKit stream. Caller pipes
 * the stream to whatever destination it needs (HTTP reply, S3 upload).
 */
export async function createCampaignLetterPdfStream(
  data: CampaignLetterPreviewData,
): Promise<InstanceType<typeof PDFDocument>> {
  const qrDataUrl = await QRCode.toDataURL(data.qrPayload, {
    width: 150,
    margin: 1,
    errorCorrectionLevel: "M",
  });
  // biome-ignore lint/style/noNonNullAssertion: data URI from QRCode.toDataURL always contains a comma separator
  const qrBuffer = Buffer.from(qrDataUrl.split(",")[1]!, "base64");

  const doc = new PDFDocument({ size: "A4", margin: 50 });

  doc.fontSize(24).text("Givernance", { align: "center" });
  doc.moveDown(0.5);
  doc.fontSize(16).text(data.campaignName, { align: "center" });
  doc.moveDown(2);

  if (data.constituent) {
    doc.fontSize(14).text("Dear Supporter", { underline: true });
    doc.fontSize(12).text(`Name: ${data.constituent.firstName} ${data.constituent.lastName}`);
    if (data.constituent.email) {
      doc.text(`Email: ${data.constituent.email}`);
    }
    doc.moveDown(1.5);
  }

  doc
    .fontSize(12)
    .text(
      data.constituent
        ? "Thank you for your continued support. We are reaching out to share our latest campaign and invite you to contribute to our mission."
        : "We are reaching out to share our latest campaign and invite you to support our mission. Your generosity makes a difference.",
    );
  doc.moveDown(1.5);

  doc.text("To learn more or donate, scan the QR code below:");
  doc.moveDown(1);

  doc.image(qrBuffer, doc.x, doc.y, { width: 150, height: 150 });
  doc.moveDown(8);

  doc.fontSize(10).text(`Reference: ${data.qrPayload}`, { align: "center" });
  doc.moveDown(2);

  doc.fontSize(10).text("This letter was generated by Givernance on behalf of your organization.", {
    align: "center",
  });

  doc.end();
  return doc;
}
